baseURL = "http://ec2-52-53-225-86.us-west-1.compute.amazonaws.com/"
languageCode = "en-us"
title = "Hugo is Awesome"
theme = "purehugo"
Paginate = 5

[params]
   twitter = "gotstago_en"
   github = "gotstago"
   google_analytics = ""
